export const GET_LIST_ADMIN = "GET_LIST_ADMIN";
export const GET_LIST_ADMIN_PAGE = "GET_LIST_ADMIN_PAGE";
export const TIM_KIEM_NGUOI_DUNG = "TIM_KIEM_NGUOI_DUNG";
export const TIM_KIEM_NGUOI_DUNG_PHAN_TRANG = "TIM_KIEM_NGUOI_DUNG_PHAN_TRANG";
export const UPDATE_ADMIN = "UPDATE_ADMIN";
export const DELETE_ADMIN = "DELATE_ADMIN";
export const DELETE_SEARCH = "DELETE_SEARCH";